### ISSUE TITLE
Hi, where should I put the Model Files, and the Dir Structure is?

### ISSUE THREAD

**Issue by beetaa** [jhj0517/ComfyUI-faster-whisper#1]
I cannot find the info, please tell, thank you.

**Comment by jhj0517** [comment]
Hi. Models should be placed on `\ComfyUI\models\faster-whisper`.

Just running the [workflow](https://github.com/jhj0517/ComfyUI-faster-whisper/blob/master/workflows/faster_whisper_suttitle.png) would automatically download models to there, but I should've specified that in the README.

**Comment by jhj0517** [comment]
Updated README in #2

**Comment by beetaa** [comment]
awesome, thank you so much for your fast reply and such many nice jobs.

**Comment by beetaa** [comment]
@jhj0517 I think I still have this problem when running with dir structure like this:

![image](https://github.com/user-attachments/assets/b7dc097d-8b95-4ea8-b3b3-0467987526a2)

but I have error as

![image](https://github.com/user-attachments/assets/1dc3c5cd-eb0e-40f3-ade9-41b6f8901a9e)

**Comment by jhj0517** [comment]
@beetaa The model should be downloaded automatically without any problem, but it seems that it is not possible to download the model programmatically?

I tried to fix it in #3 by allowing manual placement of models, including fine-tuned models. 
Can you check new version?

**Comment by beetaa** [comment]
I have tried the new version, It works perfectly, Thank you so much.

![屏幕截图 2024-09-12 075917](https://github.com/user-attachments/assets/2a3294cc-274e-4bab-83c1-8bbacadb95ce)

![屏幕截图 2024-09-12 080738](https://github.com/user-attachments/assets/41a4a248-a42a-4c22-b028-df1c7e232096)

![屏幕截图 2024-09-12 080823](https://github.com/user-attachments/assets/2acf023f-e9b2-4782-874e-13baf77f518b)
